缺失特征处理

In [25]:
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer, IterativeImputer

X = np.array([
    [1, '周末', '吃饭', 25, '不好看'],
    [2, '周末', '逛街', np.nan, '好看'],
    [3, '周末', '-', 29, '不好看'],
    [4, '周末', '逛街', 36, '好看'],
])

imp_mean = SimpleImputer(strategy='mean')
imp_mean.fit_transform(X[:, 3:4])  # 用均值填充


array([[25.],
       [30.],
       [29.],
       [36.]])

In [22]:
imp_median = SimpleImputer(strategy='median')
imp_median.fit_transform(X[:, 3:4]) # 用中位数填充

array([[25.],
       [29.],
       [29.],
       [36.]])

In [23]:
imp_frequent = SimpleImputer(missing_values='-', strategy='most_frequent')
imp_frequent.fit_transform(X[:, 2:3].astype('object')) # 用众数填充

array([['吃饭'],
       ['逛街'],
       ['逛街'],
       ['逛街']], dtype=object)

In [17]:
# 回归器默认采用BayesianRidge 也可选DecisionTreeRegressor ExtraTreesRegressor KNeighborsRegressor
imp_iter = IterativeImputer()
imp_iter.fit_transform(X[:, [0,3]])

array([[ 1.        , 25.        ],
       [ 2.        , 27.86309709],
       [ 3.        , 29.        ],
       [ 4.        , 36.        ]])