特征标准化

In [6]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler, scale

X = np.array([
    [1, '周末', '吃饭', 25, '不好看'],
    [2, '周末', '逛街', 28, '好看'],
    [3, '周末', '-', 29, '不好看'],
    [4, '周末', '逛街', 36, '好看'],
])
MinMaxScaler().fit_transform(X[:, [0,3]])

array([[0.        , 0.        ],
       [0.33333333, 0.27272727],
       [0.66666667, 0.36363636],
       [1.        , 1.        ]])

In [7]:
MaxAbsScaler().fit_transform(X[:, [0,3]])

array([[0.25      , 0.69444444],
       [0.5       , 0.77777778],
       [0.75      , 0.80555556],
       [1.        , 1.        ]])

In [8]:
x = scale(X[:, [0,3]])
x

array([[-1.34164079, -1.11631261],
       [-0.4472136 , -0.3721042 ],
       [ 0.4472136 , -0.12403473],
       [ 1.34164079,  1.61245155]])

In [12]:
x.mean(axis=0)

array([0., 0.])

In [13]:
x.std(axis=0)

array([1., 1.])