特征标准化

In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler, scale

X = np.array([
    [1, '周六', '吃饭', '晴天', '轻松', '清零', '精彩', 25.2, 0.5],
    [6, '周六', '逛街', '晴天', '轻松', '平缓', '无聊', 27.4, 2.0],
    [10, '周六', '学习', '雨天', '轻松', '严峻', '无聊', 32.6, 8.2],
    [13, '周六', '逛街', '晴天', '正常', '清零', '精彩', 36.4, 9.8],
])

MinMaxScaler().fit_transform(X[:,[0,7,8]])

array([[0.        , 0.        , 0.        ],
       [0.41666667, 0.19642857, 0.16129032],
       [0.75      , 0.66071429, 0.82795699],
       [1.        , 1.        , 1.        ]])

In [2]:
MaxAbsScaler().fit_transform(X[:,[0,7,8]])

array([[0.07692308, 0.69230769, 0.05102041],
       [0.46153846, 0.75274725, 0.20408163],
       [0.76923077, 0.8956044 , 0.83673469],
       [1.        , 1.        , 1.        ]])

In [3]:
x = scale(X[:,[0,7,8]])
x

array([[-1.44444444, -1.1861146 , -1.17034706],
       [-0.33333333, -0.68429689, -0.79077504],
       [ 0.55555556,  0.50181772,  0.77812264],
       [ 1.22222222,  1.36859377,  1.18299946]])

In [4]:
x.mean(axis=0)

array([ 5.55111512e-17,  2.22044605e-16, -5.55111512e-17])

In [5]:
x.std(axis=0)

array([1., 1., 1.])