In [34]:
import numpy as np
from sklearn.neural_network import MLPClassifier

X = np.array([[1, 1], [1, 0], [0, 1], [0, 0]])
y = np.array([0, 1, 1, 0])

mlp = MLPClassifier(
    hidden_layer_sizes=(3,),  # 隐藏层神经元个数
    activation='logistic',    # 激活函数
    max_iter=100,             # 最大迭代轮数
    solver='lbfgs',           # 求解器
    alpha=0,                  # 正则项系数
    random_state=0,
    verbose=False
)

clf = mlp.fit(X, y)
clf.score(X, y)


1.0

In [35]:
clf.predict(X)

array([0, 1, 1, 0])

In [36]:
clf.predict_proba(X)

array([[9.99657242e-01, 3.42758392e-04],
       [0.00000000e+00, 1.00000000e+00],
       [9.99000882e-12, 1.00000000e+00],
       [9.99997483e-01, 2.51712316e-06]])

In [37]:
clf.coefs_

[array([[  6.76841162, 182.00626767,  34.50952352],
        [ 13.40612336, 271.8997091 ,  20.69100835]]),
 array([[-52.19531528],
        [ 56.97435573],
        [ 59.58511557]])]

In [39]:
clf.intercepts_

[array([-13.98224375, -19.41397326,   7.64000118]), array([-72.44882658])]